- title: 'Avatar: Fire and Ash'
  year: 2025
  director: James Cameron
  country: US
  is_korean_director: false
  imdb_id: tt1757678
  imdb_url: https://www.imdb.com/title/tt1757678
  tmdb_url: https://www.themoviedb.org/movie/83533
  tmdb_title: null
  tmdb_original_title: 'Avatar: Fire and Ash'
  tmdb_original_language: English
  tmdb_director_name_1: James Cameron
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/g96wHxU7EnoIFwemb2RgohIXrgW.jpg
- title: 북촌방향
  year: 2011
  director: 홍상수
  country: Korea
  is_korean_director: true
  imdb_id: tt1922561
  imdb_url: https://www.imdb.com/title/tt1922561
  tmdb_url: https://www.themoviedb.org/movie/85525
  tmdb_title: The Day He Arrives
  tmdb_original_title: 북촌방향
  tmdb_original_language: Korean
  tmdb_director_name_1: Hong Sang-soo
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/nYgTNFSFKJMDQF4mq9vt3ieJ7eQ.jpg
- title: Zero Dark Thirty
  year: 2012
  director: Kathryn Bigelow
  country: US
  is_korean_director: false
  imdb_id: tt1790885
  imdb_url: https://www.imdb.com/title/tt1790885
  tmdb_url: https://www.themoviedb.org/movie/97630
  tmdb_title: null
  tmdb_original_title: Zero Dark Thirty
  tmdb_original_language: English
  tmdb_director_name_1: Kathryn Bigelow
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/wNSdSSxowM3WIqmPJNg3RagYbwP.jpg
- title: 방자전
  year: 2010
  director: 김대우
  country: Korea
  is_korean_director: true
  imdb_id: tt1905059
  imdb_url: https://www.imdb.com/title/tt1905059
  tmdb_url: https://www.themoviedb.org/movie/50727
  tmdb_title: The Servant
  tmdb_original_title: 방자전
  tmdb_original_language: Korean
  tmdb_director_name_1: Kim Dae-woo
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/t7vY6aU6rDNNDGFni604dk6FgIR.jpg
- title: 'Star Wars: Episode III - Revenge of the Sith'
  year: 2005
  director: George Lucas
  country: US
  is_korean_director: false
  imdb_id: tt0121766
  imdb_url: https://www.imdb.com/title/tt0121766
  tmdb_url: https://www.themoviedb.org/movie/1895
  tmdb_title: null
  tmdb_original_title: 'Star Wars: Episode III - Revenge of the Sith'
  tmdb_original_language: English
  tmdb_director_name_1: George Lucas
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg
- title: 'Star Wars: Episode II - Attack of the Clones'
  year: 2002
  director: George Lucas
  country: US
  is_korean_director: false
  imdb_id: tt0121765
  imdb_url: https://www.imdb.com/title/tt0121765
  tmdb_url: https://www.themoviedb.org/movie/1894
  tmdb_title: null
  tmdb_original_title: 'Star Wars: Episode II - Attack of the Clones'
  tmdb_original_language: English
  tmdb_director_name_1: George Lucas
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/oZNPzxqM2s5DyVWab09NTQScDQt.jpg
- title: 'Star Wars: Episode I - The Phantom Menace'
  year: 1999
  director: George Lucas
  country: US
  is_korean_director: false
  imdb_id: tt0120915
  imdb_url: https://www.imdb.com/title/tt0120915
  tmdb_url: https://www.themoviedb.org/movie/1893
  tmdb_title: null
  tmdb_original_title: 'Star Wars: Episode I - The Phantom Menace'
  tmdb_original_language: English
  tmdb_director_name_1: George Lucas
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg
- title: Children of Heaven
  year: 1997
  director: Majid Majidi
  country: Iran
  is_korean_director: false
  imdb_id: tt0118849
  imdb_url: https://www.imdb.com/title/tt0118849
  tmdb_url: https://www.themoviedb.org/movie/21334
  tmdb_title: Children of Heaven
  tmdb_original_title: بچه‌های آسمان
  tmdb_original_language: Persian
  tmdb_director_name_1: Majid Majidi
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/jWqh1CJWAEcxckMRrf6ARhIEh0R.jpg
- title: Dead Man Walking
  year: 1995
  director: Tim Robbins
  country: US
  is_korean_director: false
  imdb_id: tt0112818
  imdb_url: https://www.imdb.com/title/tt0112818
  tmdb_url: https://www.themoviedb.org/movie/687
  tmdb_title: null
  tmdb_original_title: Dead Man Walking
  tmdb_original_language: English
  tmdb_director_name_1: Tim Robbins
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/eShxyjhWoFl3BwsuEmVsr4nLaMZ.jpg
- title: Léon
  year: 1994
  director: Luc Besson
  country: France
  is_korean_director: false
  imdb_id: tt0110413
  imdb_url: https://www.imdb.com/title/tt0110413
  tmdb_url: https://www.themoviedb.org/movie/101
  tmdb_title: 'Léon: The Professional'
  tmdb_original_title: Léon
  tmdb_original_language: French
  tmdb_director_name_1: Luc Besson
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/bxB2q91nKYp8JNzqE7t7TWBVupB.jpg
- title: Basic Instinct
  year: 1992
  director: Paul Verhoeven
  country: US
  is_korean_director: false
  imdb_id: tt0103772
  imdb_url: https://www.imdb.com/title/tt0103772
  tmdb_url: https://www.themoviedb.org/movie/402
  tmdb_title: null
  tmdb_original_title: Basic Instinct
  tmdb_original_language: English
  tmdb_director_name_1: Paul Verhoeven
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/76Ts0yoHk8kVQj9MMnoMixhRWoh.jpg
- title: 'Star Wars: Return of the Jedi'
  year: 1983
  director: Richard Marquand
  country: US
  is_korean_director: false
  imdb_id: tt0086190
  imdb_url: https://www.imdb.com/title/tt0086190
  tmdb_url: https://www.themoviedb.org/movie/1892
  tmdb_title: null
  tmdb_original_title: Return of the Jedi
  tmdb_original_language: English
  tmdb_director_name_1: Richard Marquand
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/jQYlydvHm3kUix1f8prMucrplhm.jpg
- title: 'Star Wars: The Empire Strikes Back'
  year: 1980
  director: Irvin Kershner
  country: US
  is_korean_director: false
  imdb_id: tt0080684
  imdb_url: https://www.imdb.com/title/tt0080684
  tmdb_url: https://www.themoviedb.org/movie/1891
  tmdb_title: null
  tmdb_original_title: The Empire Strikes Back
  tmdb_original_language: English
  tmdb_director_name_1: Irvin Kershner
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg
- title: Star Wars
  year: 1977
  director: George Lucas
  country: US
  is_korean_director: false
  imdb_id: tt0076759
  imdb_url: https://www.imdb.com/title/tt0076759
  tmdb_url: https://www.themoviedb.org/movie/11
  tmdb_title: null
  tmdb_original_title: Star Wars
  tmdb_original_language: English
  tmdb_director_name_1: George Lucas
  tmdb_director_name_2: null
  tmdb_num_directors: 1
  tmdb_poster_url: https://image.tmdb.org/t/p/w200/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg
